apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rancher-mgr-vm
  namespace: hvst-mgmt
  labels:
    app: rancher-mgr
  annotations:
    harvesterhci.io/templateVersionId: hvst-mgmt/rancher-mgr-template
    harvesterhci.io/volumeClaimTemplates: |-
      [{
        "metadata": {
          "name": "rancher-mgr-rootdisk",
          "annotations": {
            "harvesterhci.io/imageId": "harvester-public/rocky-9-cloudimg"
          }
        },
        "spec": {
          "accessModes": ["ReadWriteMany"],
          "resources": {
            "requests": {
              "storage": "250Gi"
            }
          },
          "storageClassName": "longhorn-rocky-9-cloudimg",
          "volumeMode": "Block",
          "deleteWithVM": true
        }
      }]
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: rancher-mgr
    spec:
      domain:
        cpu:
          cores: 8
        resources:
          requests:
            memory: 32Gi
          limits:
            cpu: "8"
            memory: 32Gi
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: primary
              model: virtio
              macAddress: "02:de:ad:be:ef:02"
              bridge: {}
      networks:
        - name: primary
          multus:
            networkName: hvst-mgmt/vlan12
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: rancher-mgr-rootdisk
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: rancher-mgr-cloud-config
