apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deepflow-agent
  labels:
    app: deepflow-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: deepflow-agent
  template:
    metadata:
      labels:
        app: deepflow-agent
    spec:
      serviceAccountName: deepflow-agent-sa
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: agent
        image: {{ .Values.deepflow.agentImage | quote }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
        env:
        - name: K8S_NAMESPACE_FOR_DEEPFLOW
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_NODE_IP_FOR_DEEPFLOW
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_NODE_NAME_FOR_DEEPFLOW
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME_FOR_DEEPFLOW
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_IP_FOR_DEEPFLOW
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources: {{- toYaml .Values.resources.agent | nindent 10 }}
        volumeMounts:
        - name: sysfs
          mountPath: /host/sys
          readOnly: true
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: agent-config
          mountPath: /etc/deepflow-agent
      volumes:
      - name: sysfs
        hostPath:
          path: /sys
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: agent-config
        configMap:
          name: {{ .Release.Name }}-agent-config
      tolerations:
      - operator: Exists
