apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clickhouse
  labels:
    app: deepflow-clickhouse
spec:
  type: ClusterIP
  selector:
    app: deepflow-clickhouse
  ports:
  - port: 9000
    targetPort: native
    name: native
  - port: 8123
    targetPort: http
    name: http
