{{- if .Values.prometheusIntegration.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-deepflow-server
  namespace: {{ default .Release.Namespace .Values.prometheusIntegration.serviceMonitorNamespace }}
  labels:
    release: {{ .Values.prometheusIntegration.releaseLabel }}
    app.kubernetes.io/name: harvester-network-monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: deepflow-server
  endpoints:
  - port: api
    interval: {{ .Values.prometheusIntegration.scrapeInterval }}
    scheme: http
    path: {{ .Values.prometheusIntegration.metricsPath }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-deepflow-alerts
  namespace: {{ default .Release.Namespace .Values.prometheusIntegration.ruleNamespace }}
  labels:
    release: {{ .Values.prometheusIntegration.releaseLabel }}
    app.kubernetes.io/name: harvester-network-monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  groups:
  - name: deepflow.rules
    rules:
    - alert: DeepFlowServerUnavailable
      expr: sum(up{job="deepflow-server"}) == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: DeepFlow server is unreachable
        description: Prometheus cannot scrape the DeepFlow server metrics endpoint for more than 5 minutes.
    - alert: DeepFlowStatefulSetDegraded
      expr: kube_statefulset_status_replicas_ready{statefulset="{{ .Release.Name }}-server", namespace="{{ .Release.Namespace }}"} < {{ .Values.global.replicas }}
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: DeepFlow server replicas missing
        description: The DeepFlow server StatefulSet does not have {{ .Values.global.replicas }} ready replica(s) for at least 10 minutes.
{{- end }}
