apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkpolicy-mysql-clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: deepflow-server
    - podSelector:
        matchLabels:
          app: deepflow-grafana
    ports:
    - protocol: TCP
      port: 3306
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 8123
