apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: deepflow-server
spec:
  type: ClusterIP
  selector:
    app: deepflow-server
  ports:
  - name: querier
    port: {{ .Values.deepflow.ports.querier }}
    targetPort: querier-port
  - name: data
    port: {{ .Values.deepflow.ports.data }}
    targetPort: data-port
  - name: api
    port: {{ .Values.deepflow.ports.api }}
    targetPort: api-port
  - name: otel
    port: {{ .Values.deepflow.ports.otel }}
    targetPort: otel-port
